import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function TelemetryDashboard({ metrics }) {
    const MetricCard = ({ label, value, unit = 'ms', target = 1200, }) => {
        const percentage = (value / target) * 100;
        const isGood = percentage < 50;
        const isOkay = percentage < 80;
        const color = isGood ? 'bg-green-600' : isOkay ? 'bg-amber-600' : 'bg-red-600';
        const roundedValue = value.toFixed(5);
        return (_jsxs("div", { className: "bg-slate-700 rounded-lg p-4", children: [_jsx("p", { className: "text-sm text-slate-400 mb-2", children: label }), _jsxs("div", { className: "flex items-end gap-2 mb-2", children: [_jsx("span", { className: "text-3xl font-bold", children: roundedValue }), _jsx("span", { className: "text-sm text-slate-400", children: unit })] }), _jsx("div", { className: "w-full bg-slate-600 rounded-full h-2 overflow-hidden", children: _jsx("div", { className: `h-full ${color} transition-all duration-300`, style: { width: `${Math.min(percentage, 100)}%` } }) }), _jsxs("p", { className: "text-xs text-slate-400 mt-2", children: ["Target: <", target, unit] })] }));
    };
    return (_jsxs("div", { className: "bg-slate-800 border border-slate-700 rounded-lg p-6", children: [_jsx("h2", { className: "text-lg font-semibold mb-4", children: "Latency Metrics (P-percentiles)" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsx(MetricCard, { label: "P50 (Median)", value: metrics.p50_ms, target: 1200 }), _jsx(MetricCard, { label: "P95 (95th %ile)", value: metrics.p95_ms, target: 1200 }), _jsx(MetricCard, { label: "P99 (99th %ile)", value: metrics.p99_ms, target: 1800 })] }), _jsxs("div", { className: "mt-6 bg-slate-700 rounded-lg p-4", children: [_jsx("h3", { className: "font-semibold text-sm mb-3", children: "Latency Budget Breakdown" }), _jsxs("div", { className: "space-y-2 text-xs text-slate-400", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "ASR (Speech Recognition)" }), _jsx("span", { className: "font-mono", children: "500 ms" })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "LLM (Time to First Token)" }), _jsx("span", { className: "font-mono", children: "400 ms" })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "TTS (Time to First Byte)" }), _jsx("span", { className: "font-mono", children: "250 ms" })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Orchestration Overhead" }), _jsx("span", { className: "font-mono", children: "100 ms" })] }), _jsxs("div", { className: "border-t border-slate-600 pt-2 mt-2 flex justify-between font-semibold text-white", children: [_jsx("span", { children: "Total E2E (P95)" }), _jsx("span", { className: "font-mono", children: "1,200 ms" })] })] })] }), _jsxs("div", { className: "mt-6 bg-slate-700 rounded-lg p-4", children: [_jsx("h3", { className: "font-semibold text-sm mb-2", children: "System Status" }), _jsxs("ul", { className: "text-xs text-slate-400 space-y-1", children: [_jsx("li", { children: "\u2713 Circuit breakers: Per-service resilience" }), _jsx("li", { children: "\u2713 Fallback strategies: Bridge audio on failure" }), _jsx("li", { children: "\u2713 10-turn context: Conversation history maintained" }), _jsx("li", { children: "\u2713 Barge-in support: Interrupt in-progress responses" }), _jsx("li", { children: "\u2713 Session replay: Record & playback for debugging" })] })] })] }));
}
